### PR TITLE
Use two visitors to find deferreds

### LINKED ISSUE #2: Fails to identify defers in nested BlockStmt
Defers in nested `BlockStmt` are not detected.

```go
package main

import (
	"fmt"
)

func main() {
	for i := 0; i < 5; i++ {
		defer fmt.Println("Hello, playground")
		{
			defer fmt.Println("Hello, playground") //Not detected
		}
		fmt.Println(i)
	}
}
```

Bug is in https://github.com/gsquire/dll/blob/adb0f52593d650e8e278f6b59e6ad0db22845ab1/dll.go#L42-L50

Instead of looking into the `BlockStmt` of the for loop all child elements have to be checked. I haven't worked much with `ast` package, but I'd assume that you'd need another walker+visitor here.

### PR DESCRIPTION
**Pull request by icholy**
Fix #2  and lots of similar cases.

### CODE REVIEW

**Comment by gsquire** [comment]
Thanks for submitting this! Would you mind adding one more test case with an `if` statement? This was another case I had forgotten before.

Otherwise this LGTM.

**Comment by icholy** [comment]
I won't be able to update this till monday.

**Comment by icholy** [comment]
Also, we should reset it back to `findLoop` if we're entering a function literal.

**Comment by icholy** [comment]
@gsquire I've updated it

**Comment by gsquire** [comment]
@icholy Thanks for this awesome PR! Merged.

**Pull request merged**
